### ISSUE TITLE
Is it possible to filter public and private user?

### ISSUE THREAD

**Issue by hyppplernthn** [Na-Bo00/instagram-follower-scraper#2]
Would there be a way to grab data "isPrivate" to be able to filter the xcel file to only public profiles for automation

**Comment by NaBo-00** [comment]
This is not possible in the current version but this feature can be added if required. 
Kind regards

**Comment by NaBo-00** [comment]
> Would there be a way to grab data "isPrivate" to be able to filter the xcel file to only public profiles for automation

This is not possible in the current version but this feature can be added if required.
Kind regards
